In [61]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
import numpy as np

# Graph

In [ ]:
# a = tf.constant(2)
# b = tf.constant(3)
# x = tf.add(a, b)
# writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
# with tf.Session() as sess:
#     print(sess.run(x))
# writer.close()

In [ ]:
# !tensorboard --logdir ./graphs --port 6006

In [2]:
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(a, b, name="add")

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
writer.close()

5


# Constant

In [3]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='mul')
with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


In [4]:
tf.Session().run(tf.zeros([2, 3], tf.int32)) # [[0, 0, 0], [0, 0, 0]]

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [5]:
tf.Session().run(tf.ones([2, 3]))

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [6]:
input_tensor = [[0, 1], [2, 3], [4, 5]]
tf.Session().run(tf.zeros_like(input_tensor))

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [7]:
tf.Session().run(tf.ones_like(input_tensor))

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [20]:
print(tf.fill([2,3],8, name="fill"))
tf.Session().run(tf.fill([2,3],8))

Tensor("fill_9:0", shape=(2, 3), dtype=int32)


array([[8, 8, 8],
       [8, 8, 8]], dtype=int32)

In [22]:
print(tf.lin_space(1.,5.,5, name="linspace"))
tf.Session().run(tf.lin_space(1.,5.,5))

Tensor("linspace_9:0", shape=(5,), dtype=float32)


array([1., 2., 3., 4., 5.], dtype=float32)

In [26]:
tf.range(0,10,2)
tf.Session().run(tf.range(0,10,2))

array([0, 2, 4, 6, 8], dtype=int32)

# Random

In [ ]:
# tf.random_normal
# tf.truncated_normal
# tf.random_uniform
# tf.random_shuffle
# tf.random_crop
# tf.multinomial
# tf.random_gamma

In [27]:
tf.set_random_seed(1)

In [36]:
tf.Session().run(tf.random_normal((5,)))

array([-0.17469783,  0.51620245,  0.24235971, -0.5863313 ,  0.7638169 ],
      dtype=float32)

In [40]:
tf.Session().run(tf.truncated_normal((5,2)))

array([[ 0.8562012 ,  0.43197668],
       [-0.79988956,  0.97523725],
       [ 1.2264111 , -1.2610478 ],
       [-1.7540636 , -1.8585725 ],
       [-1.2803365 , -0.4149142 ]], dtype=float32)

# Operation

In [ ]:
# tf.abs
# tf.negative
# tf.sign
# tf.reciprocal
# tf.square
# tf.round
# tf.sqrt
# tf.rsqrt
# tf.pow
# tf.exp

In [42]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
with tf.Session() as sess:
    print(sess.run(tf.div(b, a)))             # ⇒ [[0 0] [1 1]]
    print(sess.run(tf.divide(b, a)))          # ⇒ [[0. 0.5] [1. 1.5]]
    print(sess.run(tf.truediv(b, a)))         # ⇒ [[0. 0.5] [1. 1.5]]
    print(sess.run(tf.floordiv(b, a)))        # ⇒ [[0 0] [1 1]]
#     print(sess.run(tf.realdiv(b, a)))         # ⇒ # Error: only works for real values
    print(sess.run(tf.truncatediv(b, a)))     # ⇒ [[0 0] [1 1]]
    print(sess.run(tf.floor_div(b, a))) 


[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


# Data Type

In [44]:
t_0 = 19
print(tf.Session().run(tf.zeros_like(t_0)))
print(tf.Session().run(tf.ones_like(t_0)))

0
1


In [47]:
t_1 = [b"apple", b"peach", b"grape"]
print(tf.Session().run(tf.zeros_like(t_1)))
# print(tf.Session().run(tf.ones_like(t_1))) ## ==> TypeError: Expected string, got 1 of type 'int' instead.


[b'' b'' b'']


In [49]:
t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]] 
print(tf.Session().run(tf.zeros_like(t_2)))
print(tf.Session().run(tf.ones_like(t_2)))

[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [51]:
tf.int32 == np.int32

True

In [52]:
tf.ones([2,2], np.float64)

<tf.Tensor 'ones_1:0' shape=(2, 2) dtype=float64>

In [55]:
sess=tf.Session()
a = tf.zeros([2,3], np.int32)
print(type(a))
a_out = sess.run(a)
print(type(a_out))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


In [59]:
tf.reset_default_graph()

my_const = tf.constant([1.0, 2.0], name="my_const")
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "my_const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\200?\000\000\000@"
      }
    }
  }
}
versions {
  producer: 27
}



# Variable

In [77]:
tf.reset_default_graph()

# create variables with tf.Variable
s = tf.Variable(2, name="scalar")
m = tf.Variable([[0, 1], [2, 3]], name="matrix")
W = tf.Variable(tf.zeros([784,10]))

# create variables with tf.get_variable
s = tf.get_variable("scalar", initializer=tf.constant(2)) 
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())

In [75]:
x = tf.Variable(2) 

# x.initializer # init op
# x.value() # read op
# x.assign(...) # write op
# x.assign_add(...) # and more


Tensor("Variable_5/read:0", shape=(), dtype=int32)


In [83]:
# The easiest way is initializing all variables at once
with tf.Session() as sess:
    # print(sess.run(W)) # FailedPreconditionError: Attempting to use uninitialized value Variable
    sess.run(tf.global_variables_initializer())
    
    print(sess.run({"s":s, "m":m}))

{'s': 2, 'm': array([[0, 1],
       [2, 3]], dtype=int32)}


In [88]:
#Initialize only a subset of variables
with tf.Session() as sess:
    sess.run(tf.variables_initializer([s, m]))
    print(m)
    print(m.eval())

<tf.Variable 'matrix_1:0' shape=(2, 2) dtype=int32_ref>
[[0 1]
 [2 3]]


In [89]:
#Initialize a single variable
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W)
    

<tf.Variable 'big_matrix:0' shape=(784, 10) dtype=float32_ref>


In [98]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval()) 
    sess.run(assign_op)
    print(W.eval()) 

10
100


In [102]:
# create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var") 

# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer) #2
    sess.run(my_var_times_two)   #4
    sess.run(my_var_times_two)   #8
    sess.run(my_var.assign_add(10)) # 18
    sess.run(my_var.assign_sub(2)) # 16

    print(my_var.eval())

16


In [104]:
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10))) # >> 20
print(sess2.run(W.assign_sub(2)))  # >> 8

print(sess1.run(W.assign_add(100))) # >> 120
print(sess2.run(W.assign_sub(50)))  # >> -42

sess1.close()
sess2.close()


20
8
120
-42


In [111]:
# defines which ops should be run first
# your graph g have 5 ops: a, b, c, d, e
a = tf.add(1,2)
b = tf.add(1,2)
c = tf.add(1,2)
g = tf.get_default_graph()
with g.control_dependencies([a, b, c]):
    # 'd' and 'e' will only run after 'a', 'b', and 'c' have executed.
    d = tf.add(a,c)
    e = tf.add(a,b)

# Placeholder

In [130]:
tf.reset_default_graph()

a = tf.placeholder(tf.float32, shape=[3], name="a")
b = tf.constant([5,5,5], tf.float32, name="b")
c = a + b # short for tf.add(a,b)

writer = tf.summary.FileWriter("./graphs", tf.get_default_graph())
with tf.Session() as sess:
#     print(sess.run(c))   #InvalidArgumentError: a doesn’t an actual value

    print(sess.run(c, feed_dict={a: [1,2,3]}))
    print(sess.run(c, {a: [1,2,3]}))
writer.close()

[6. 7. 8.]
[6. 7. 8.]


In [129]:
list_of_values_for_a = np.array(range(9)).reshape(-1,3)
with tf.Session() as sess:
    for a_value in list_of_values_for_a:
        print(sess.run(c, {a: a_value}))


[5. 6. 7.]
[ 8.  9. 10.]
[11. 12. 13.]


In [133]:
tf.get_default_graph().is_feedable(c)

True

In [135]:
# create operations, tensors, etc (using the default graph)
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    # compute the value of b given a is 15
    print(sess.run(b, feed_dict={a: 15})) 

45


# Lazy loading

In [143]:
tf.reset_default_graph()
# Normal loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y)  # create the node before executing the graph

writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(z)
writer.close()
tf.get_default_graph().as_graph_def()

node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input

In [144]:
tf.reset_default_graph()
# Lazy loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

writer = tf.summary.FileWriter('./graphs/lazy_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(tf.add(x, y)) # someone decides to be clever to save one line of code
writer.close()
tf.get_default_graph().as_graph_def()

node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input

In [ ]:
# Solution
# Separate definition of ops from computing/running ops 
# Use Python property to ensure function is also loaded once the first time it is called*
